############################
# cert-manager
############################
cert-manager:
  global:
    leaderElection:
      namespace: kube-system

############################
# KServe Controller
############################
controller:
  deploymentMode: Serverless
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

webhook:
  enabled: true