apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/iamkeerthik/mlops-demo-project'
    targetRevision: main
    path: mlops/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true