apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: model-1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/<your-org>/<your-repo>.git'
    targetRevision: main
    path: 'mlops/apps/model-1'   # <-- folder containing deploy.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true