# File: terraform-helm/addons/argocd/values/mlops-apps/model-1-dev.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-1
  namespace: mlops
  labels:
    app: model-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-1
  template:
    metadata:
      labels:
        app: model-1
    spec:
      containers:
        - name: model-1
          image: 688349427813.dkr.ecr.ap-south-1.amazonaws.com/app:model1-dev-5005f8e
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: model-1-service
  namespace: mlops
spec:
  selector:
    app: model-1
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001